---
version: '3.7'

services:
  emby:
    image: "emby/embyserver:4.7.0.3"
    container_name: "emby"
    environment:
      - "UID=$USER_ID"
      - "GID=$GROUP_ID"
      - "GIDLIST=$EMBY_GIDLIST"
    networks:
      - "traefik"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./emby:/config"
      - "/home/lotus/docker/media/media/radarr/movies:/mnt/movies"
      - "/home/lotus/docker/media/media/sonarr/series:/mnt/tvshows"
      - "/home/lotus/docker/media/media/documentaries:/mnt/documentairies"
    devices:
      - "/dev/dri:/dev/dri"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.rule=Host(`emby.${DOMAIN_NAME}`)"
      - "traefik.http.routers.emby.entrypoints=websecure"
      - "traefik.http.routers.emby.tls.certresolver=myresolver"
      - "traefik.http.services.emby.loadbalancer.server.port=8096"

  transmission:
    image: "linuxserver/transmission:version-3.00-r2"
    container_name: "transmission"
    environment:
      - "PUID=$USER_ID"
      - "PGID=$GROUP_ID"
    networks:
      - "traefik"
    ports:
      - "51413:51413/tcp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./transmission:/config"
      - "/home/lotus/docker/media/media/transmission/downloads:/downloads"
    logging:
      driver: none
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`dl.${DOMAIN_NAME}`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls.certresolver=myresolver"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"

  jackett:
    image: "linuxserver/jackett:version-v0.18.455"
    container_name: "jackett"
    environment:
      - "PUID=$USER_ID"
      - "PGID=$GROUP_ID"
    networks:
      - "traefik"
    volumes:
      - "./jackett:/config"
      - "/home/lotus/docker/media/media/transmission/downloads:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN_NAME}`)"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls.certresolver=myresolver"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"

  sonarr:
    image: "linuxserver/sonarr:version-3.0.6.1265"
    container_name: "sonarr"
    environment:
      - "PUID=$USER_ID"
      - "PGID=$GROUP_ID"
    networks:
      - "traefik"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./sonarr:/config"
      - "/home/lotus/docker/media/media/sonarr/series:/tv"
      - "/home/lotus/docker/media/media/transmission/downloads:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`series.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    depends_on:
      - "transmission"
      - "jackett"

  radarr:
    image: "linuxserver/radarr:version-3.2.2.5080"
    container_name: "radarr"
    environment:
      - "PUID=$USER_ID"
      - "PGID=$GROUP_ID"
    networks:
      - "traefik"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./radarr:/config"
      - "/home/lotus/docker/media/media/radarr/movies:/movies"
      - "/home/lotus/docker/media/media/transmission/downloads:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`films.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    depends_on:
      - "transmission"
      - "jackett"

networks:
  traefik:
    external: true
