#!/usr/bin/env ansible-playbook

- hosts: all
  handlers:
    - name: Restart OpenSSH Server service
      become: yes
      service:
        name: "sshd"
        state: restarted
      listen: Restart firewall

    - name: Restart nftables service
      become: yes
      service:
        name: "nftables"
        state: restarted

    - name: Restart docker service
      become: yes
      service:
        name: "docker"
        state: restarted
      listen: Restart firewall

  tasks:
    - include_tasks: tasks/packages.yml

    - include_tasks: tasks/opensshd.yml

    - include_tasks: tasks/nftables.yml

    - include_tasks: tasks/docker.yml

    - include_tasks: tasks/app_management.yml
      vars:
        app_name: "traefik"
        app_src: files/apps/traefik/
        app_env: |
          ACME_EMAIL={{ domain_name_acme_email }}

    - include_tasks: tasks/monitoring.yml

    - include_tasks: tasks/app_management.yml
      vars:
        app_name: "{{ outer_item.name }}"
        app_src: "{{ outer_item.src }}"
        app_env: "{{ outer_item.env | default('') }}"
      loop: "{{ apps }}"
      loop_control:
        loop_var: "outer_item"

    - name: Cleanup docker images/network/…
      become: yes
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
        builder_cache: yes
