#!/usr/bin/env ansible-playbook

- hosts: all
  tasks:
    - name: Packages | Perform upgrade
      become: yes
      register: upgraded
      package:
        update_cache: yes
        upgrade: yes

    - block:
        - debug:
            var: upgraded.packages

        - pause:
            prompt: "Press enter to continue… You may want to restart your server before (review the packages updated)."
      when: upgraded.changed

    - include_role:
        name: my.openssh
    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers

    - include_role:
        name: my.nftables_docker
    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers

    - include_role:
        name: my.docker_compose
