---

- name: docker | Install Docker via package manager
  become: yes
  pacman:
    name:
      - "docker"
    state: present

- name: docker | Enable Docker service
  become: yes
  service:
    name: "docker"
    enabled: yes
