---

- name: nftables_docker | Install docker
  become: yes
  pacman:
    name:
      - "docker"
      - "docker-compose"
    state: present

- name: nftables_docker | Enable Docker service
  become: yes
  service:
    name: "docker"
    enabled: yes
