---

- name: docker | Install Docker tools
  become: yes
  pacman:
    name:
      - "docker"
      - "docker-compose"
    state: present

- name: docker | Enable Docker service
  become: yes
  service:
    name: "docker"
    enabled: yes
