---

- name: OpenSSH Server | Install configuration
  become: yes
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: "root"
    group: "root"
    mode: 0600
    validate: "/usr/bin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s"
  notify: Restart OpenSSH Server service

- name: OpenSSH Server | Check weak moduli
  shell: "gawk '$5 < 3071' /etc/ssh/moduli"
  register: openssh_register_moduli
  changed_when: false
  check_mode: no

- name: OpenSSH Server | Replace weak moduli
  become: yes
  shell: "gawk -i inplace -v INPLACE_SUFFIX=.bak '$5 >= {{ openssh_moduli_minimum }}' /etc/ssh/moduli"
  notify: Restart OpenSSH Server service
  when: openssh_register_moduli.stdout
