---

- name: Packages | Perform upgrade
  become: yes
  register: upgraded
  package:
    update_cache: yes
    upgrade: yes

- block:
    - debug:
        var: upgraded.packages

    - pause:
        prompt: "Review updated packages! Then restart your server if needed and/or press enter to continue…"
  when: upgraded.changed
