---

- name: nftables_docker | Restart nftables service
  become: yes
  service:
    name: nftables
    state: restarted

- name: nftables_docker | Restart Docker service
  become: yes
  service:
    name: docker
    state: restarted
