---
version: '3.7'

services:
  heimdall:
    image: "linuxserver/heimdall:2.4.8"
    container_name: "heimdall"
    environment:
      - "PUID=$USER_ID"
      - "PGID=$GROUP_ID"
      - "TZ=$TZ"
    networks:
      - "traefik"
    volumes:
      - "./config:/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls.certresolver=myresolver"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
