---
version: '3.7'
# See the excellent work from:
# https://github.com/stefanprodan/dockprom

networks:
  traefik:
    external: true
  monitoring:
    name: "monitoring"
    ipam:
      driver: "default"
      config:
        - subnet: "172.42.0.0/24"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: "prom/prometheus:v2.40.5"
    container_name: "prometheus"
    volumes:
      - "./prometheus:/etc/prometheus"
      - "prometheus_data:/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      monitoring:
        ipv4_address: "172.42.0.10"
      traefik:
    labels:
      - "org.label-schema.group=monitoring"

  alertmanager:
    image: "prom/alertmanager:v0.24.0"
    container_name: "alertmanager"
    volumes:
      - "./alertmanager:/etc/alertmanager"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - "monitoring"
      - "traefik"
    labels:
      - "org.label-schema.group=monitoring"

  karma:
    image: "lmierzwa/karma:v0.110"
    container_name: "karma"
    networks:
      - "monitoring"
      - "traefik"
    environment:
      - "ALERTMANAGER_URI=http://alertmanager:9093"
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.enable=true"
      - "traefik.http.routers.karma.rule=Host(`karma.$DOMAIN_NAME`)"
      - "traefik.http.routers.karma.entrypoints=websecure"
      - "traefik.http.routers.karma.tls.certresolver=myresolver"
      - "traefik.http.services.karma.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik"

  cadvisor:
    image: "gcr.io/google-containers/cadvisor:v0.36.0"
    container_name: "cadvisor"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
      - "/dev/disk:/dev/disk:ro"
    networks:
      - "monitoring"
    labels:
      - "org.label-schema.group=monitoring"

  grafana:
    image: "grafana/grafana:8.5.15"
    container_name: "grafana"
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    environment:
      - "GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}"
      - "GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    networks:
      - "monitoring"
      - "traefik"
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.$DOMAIN_NAME`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"
